name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - python=3.10.9
  - mlflow=2.0.1
  - scikit-learn
  - matplotlib
  - pillow
  - pip:
      - wandb==0.13.9
